
server:
  port: 8079
  servlet:
    context-path: /netty_client

# 通过zk维护netty地址
zookeeper:
  register:
    address: 120.79.128.43
    root_dir: /rpc


# spring-boot-starter-parent自带各种logging依赖，只需指定logback配置和日志路径即可
logging:
  config: classpath:logback.xml
  file:
    path: /log